[2025-04-06T03:26:02.222+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T03:26:02.232+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: la_traffic_download_to_bq_via_url.load_csv_to_bigquery manual__2025-04-06T03:24:49.086499+00:00 [queued]>
[2025-04-06T03:26:02.236+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: la_traffic_download_to_bq_via_url.load_csv_to_bigquery manual__2025-04-06T03:24:49.086499+00:00 [queued]>
[2025-04-06T03:26:02.238+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-06T03:26:02.244+0000] {taskinstance.py:2890} INFO - Executing <Task(GCSToBigQueryOperator): load_csv_to_bigquery> on 2025-04-06 03:24:49.086499+00:00
[2025-04-06T03:26:02.248+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-06T03:26:02.248+0000] {standard_task_runner.py:72} INFO - Started process 185 to run task
[2025-04-06T03:26:02.249+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'la_traffic_download_to_bq_via_url', 'load_csv_to_bigquery', 'manual__2025-04-06T03:24:49.086499+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmplazxz14h']
[2025-04-06T03:26:02.249+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask load_csv_to_bigquery
[2025-04-06T03:26:02.274+0000] {task_command.py:467} INFO - Running <TaskInstance: la_traffic_download_to_bq_via_url.load_csv_to_bigquery manual__2025-04-06T03:24:49.086499+00:00 [running]> on host 43216fd05265
[2025-04-06T03:26:02.309+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='la_traffic_download_to_bq_via_url' AIRFLOW_CTX_TASK_ID='load_csv_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T03:24:49.086499+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T03:24:49.086499+00:00'
[2025-04-06T03:26:02.310+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-06T03:26:02.310+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-06T03:26:02.310+0000] {logging_mixin.py:190} INFO - Current task name:load_csv_to_bigquery state:running start_date:2025-04-06 03:26:02.232982+00:00
[2025-04-06T03:26:02.311+0000] {logging_mixin.py:190} INFO - Dag name:la_traffic_download_to_bq_via_url and current dag run status:running
[2025-04-06T03:26:02.311+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T03:26:02.312+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-06T03:26:02.312+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud) shall not contain '_' according to RFC3986.
[2025-04-06T03:26:02.313+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-06T03:26:02.315+0000] {gcs_to_bigquery.py:389} INFO - Using existing BigQuery table for storing data...
[2025-04-06T03:26:02.315+0000] {credentials_provider.py:402} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-04-06T03:26:02.351+0000] {gcs_to_bigquery.py:393} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'taxi-rides-ny-450705', 'datasetId': 'la_traffic_collision', 'tableId': 'traffic_collisions'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://la-traffic-collision/traffic-collision-data-from-2010-to-present.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2025-04-06T03:26:02.352+0000] {bigquery.py:1241} INFO - Inserting job ***_la_traffic_download_to_bq_via_url_load_csv_to_bigquery_2025_04_06T03_24_49_086499_00_00_2d986c7a65e9f4b6ce0c512514fdc03f
[2025-04-06T03:26:03.753+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 458, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Field name 'Neighborhood Councils (Certified)' is not supported by the current character map. Please change your field name or use character map V2 to let the system modify the field names.; reason: invalidQuery, location: query, message: Field name 'Neighborhood Councils (Certified)' is not supported by the current character map. Please change your field name or use character map V2 to let the system modify the field names.
[2025-04-06T03:26:03.759+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-06T03:26:03.760+0000] {logging_mixin.py:190} INFO - Task start:2025-04-06 03:26:02.232982+00:00 end:2025-04-06 03:26:03.759701+00:00 duration:1.526719
[2025-04-06T03:26:03.760+0000] {logging_mixin.py:190} INFO - Task:<Task(GCSToBigQueryOperator): load_csv_to_bigquery> dag:<DAG: la_traffic_download_to_bq_via_url> dagrun:<DagRun la_traffic_download_to_bq_via_url @ 2025-04-06 03:24:49.086499+00:00: manual__2025-04-06T03:24:49.086499+00:00, state:running, queued_at: 2025-04-06 03:24:49.109200+00:00. externally triggered: True>
[2025-04-06T03:26:03.760+0000] {logging_mixin.py:190} INFO - Failure caused by 400 Field name 'Neighborhood Councils (Certified)' is not supported by the current character map. Please change your field name or use character map V2 to let the system modify the field names.; reason: invalidQuery, location: query, message: Field name 'Neighborhood Councils (Certified)' is not supported by the current character map. Please change your field name or use character map V2 to let the system modify the field names.
[2025-04-06T03:26:03.760+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=la_traffic_download_to_bq_via_url, task_id=load_csv_to_bigquery, run_id=manual__2025-04-06T03:24:49.086499+00:00, execution_date=20250406T032449, start_date=20250406T032602, end_date=20250406T032603
[2025-04-06T03:26:03.773+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T03:26:03.774+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 34 for task load_csv_to_bigquery (400 Field name 'Neighborhood Councils (Certified)' is not supported by the current character map. Please change your field name or use character map V2 to let the system modify the field names.; reason: invalidQuery, location: query, message: Field name 'Neighborhood Councils (Certified)' is not supported by the current character map. Please change your field name or use character map V2 to let the system modify the field names.; 185)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 458, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Field name 'Neighborhood Councils (Certified)' is not supported by the current character map. Please change your field name or use character map V2 to let the system modify the field names.; reason: invalidQuery, location: query, message: Field name 'Neighborhood Councils (Certified)' is not supported by the current character map. Please change your field name or use character map V2 to let the system modify the field names.
[2025-04-06T03:26:03.808+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-06T03:26:03.822+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T03:26:03.822+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
